[package]
name = "shale"
version = "0.1.0"
authors = ["Elekrisk <einar.vilhelm.persson@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
trace = ["peg/trace"]

[dependencies]
num-bigint = "0.3"
peg = "0.6"
